HEXAGRAMAS_INFO = {
    1: {"Nombre": "Lo Creativo", "Caracter": "乾", "Pinyin": "Qián"},
    2: {"Nombre": "Lo Receptivo", "Caracter": "坤", "Pinyin": "Kūn"},
    3: {"Nombre": "La dificultad inicial", "Caracter": "屯", "Pinyin": "Zhūn"},
    4: {"Nombre": "La necedad juvenil", "Caracter": "蒙", "Pinyin": "Méng"},
    5: {"Nombre": "La espera", "Caracter": "需", "Pinyin": "Xū"},
    6: {"Nombre": "El conflicto", "Caracter": "訟", "Pinyin": "Sòng"},
    7: {"Nombre": "El ejército", "Caracter": "師", "Pinyin": "Shī"},
    8: {"Nombre": "La solidaridad", "Caracter": "比", "Pinyin": "Bǐ"},
    9: {"Nombre": "El poder de lo débil", "Caracter": "小畜", "Pinyin": "Xiǎo Chù"},
    10: {"Nombre": "Conducción", "Caracter": "履", "Pinyin": "Lǚ"},
    11: {"Nombre": "La paz", "Caracter": "泰", "Pinyin": "Tài"},
    12: {"Nombre": "El estancamiento", "Caracter": "否", "Pinyin": "Pǐ"},
    13: {"Nombre": "La comunidad con los hombres", "Caracter": "同人", "Pinyin": "Tóng Rén"},
    14: {"Nombre": "La posesión de lo grande", "Caracter": "大有", "Pinyin": "Dà Yǒu"},
    15: {"Nombre": "La modestia", "Caracter": "謙", "Pinyin": "Qiān"},
    16: {"Nombre": "El entusiasmo", "Caracter": "豫", "Pinyin": "Yù"},
    17: {"Nombre": "El seguimiento", "Caracter": "隨", "Pinyin": "Suí"},
    18: {"Nombre": "La corrección de lo corrupto", "Caracter": "蠱", "Pinyin": "Gǔ"},
    19: {"Nombre": "El acercamiento", "Caracter": "臨", "Pinyin": "Lín"},
    20: {"Nombre": "La contemplación", "Caracter": "觀", "Pinyin": "Guān"},
    21: {"Nombre": "La mordedura tajante", "Caracter": "噬嗑", "Pinyin": "Shì Kè"},
    22: {"Nombre": "La gracia", "Caracter": "賁", "Pinyin": "Bì"},
    23: {"Nombre": "La disolución", "Caracter": "剝", "Pinyin": "Bō"},
    24: {"Nombre": "El retorno", "Caracter": "復", "Pinyin": "Fù"},
    25: {"Nombre": "La inocencia", "Caracter": "無妄", "Pinyin": "Wú Wàng"},
    26: {"Nombre": "El poder de lo grande", "Caracter": "大畜", "Pinyin": "Dà Chù"},
    27: {"Nombre": "La nutrición", "Caracter": "頤", "Pinyin": "Yí"},
    28: {"Nombre": "La preponderancia de lo grande", "Caracter": "大過", "Pinyin": "Dà Guò"},
    29: {"Nombre": "Lo abismal", "Caracter": "坎", "Pinyin": "Kǎn"},
    30: {"Nombre": "Lo adherente", "Caracter": "離", "Pinyin": "Lí"},
    31: {"Nombre": "La influencia", "Caracter": "咸", "Pinyin": "Xián"},
    32: {"Nombre": "La duración", "Caracter": "恆", "Pinyin": "Héng"},
    33: {"Nombre": "La retirada", "Caracter": "遯", "Pinyin": "Dùn"},
    34: {"Nombre": "El poder de lo grande", "Caracter": "大壯", "Pinyin": "Dà Zhuàng"},
    35: {"Nombre": "El progreso", "Caracter": "晉", "Pinyin": "Jìn"},
    36: {"Nombre": "El oscurecimiento de la luz", "Caracter": "明夷", "Pinyin": "Míng Yí"},
    37: {"Nombre": "La familia", "Caracter": "家人", "Pinyin": "Jiā Rén"},
    38: {"Nombre": "La oposición", "Caracter": "睽", "Pinyin": "Kuí"},
    39: {"Nombre": "El obstáculo", "Caracter": "蹇", "Pinyin": "Jiǎn"},
    40: {"Nombre": "La liberación", "Caracter": "解", "Pinyin": "Xiè"},
    41: {"Nombre": "La disminución", "Caracter": "損", "Pinyin": "Sǔn"},
    42: {"Nombre": "El aumento", "Caracter": "益", "Pinyin": "Yì"},
    43: {"Nombre": "La resolución", "Caracter": "夬", "Pinyin": "Guài"},
    44: {"Nombre": "El venir al encuentro", "Caracter": "姤", "Pinyin": "Gòu"},
    45: {"Nombre": "La reunión", "Caracter": "萃", "Pinyin": "Cuì"},
    46: {"Nombre": "El ascenso", "Caracter": "升", "Pinyin": "Shēng"},
    47: {"Nombre": "La opresión", "Caracter": "困", "Pinyin": "Kùn"},
    48: {"Nombre": "El pozo", "Caracter": "井", "Pinyin": "Jǐng"},
    49: {"Nombre": "La revolución", "Caracter": "革", "Pinyin": "Gé"},
    50: {"Nombre": "El caldero", "Caracter": "鼎", "Pinyin": "Dǐng"},
    51: {"Nombre": "Lo suscitativo", "Caracter": "震", "Pinyin": "Zhèn"},
    52: {"Nombre": "Lo inmovilizador", "Caracter": "艮", "Pinyin": "Gèn"},
    53: {"Nombre": "El desarrollo", "Caracter": "漸", "Pinyin": "Jiàn"},
    54: {"Nombre": "La desposada", "Caracter": "歸妹", "Pinyin": "Guī Mèi"},
    55: {"Nombre": "La abundancia", "Caracter": "豐", "Pinyin": "Fēng"},
    56: {"Nombre": "El viajero", "Caracter": "旅", "Pinyin": "Lǚ"},
    57: {"Nombre": "Lo penetrante", "Caracter": "巽", "Pinyin": "Xùn"},
    58: {"Nombre": "Lo sereno", "Caracter": "兌", "Pinyin": "Duì"},
    59: {"Nombre": "La dispersión", "Caracter": "渙", "Pinyin": "Huàn"},
    60: {"Nombre": "La limitación", "Caracter": "節", "Pinyin": "Jié"},
    61: {"Nombre": "La verdad interior", "Caracter": "中孚", "Pinyin": "Zhōng Fú"},
    62: {"Nombre": "La preponderancia de lo pequeño", "Caracter": "小過", "Pinyin": "Xiǎo Guò"},
    63: {"Nombre": "Después de la consumación", "Caracter": "既濟", "Pinyin": "Jì Jì"},
    64: {"Nombre": "Antes de la consumación", "Caracter": "未濟", "Pinyin": "Wèi Jì"},
}
